// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "account_type", Type: field.TypeEnum, Enums: []string{"checking", "savings", "credit", "cash", "investment"}, Default: "checking"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "country_id", Type: field.TypeInt},
		{Name: "currency_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "accounts_countries_accounts",
				Columns:    []*schema.Column{AccountsColumns[5]},
				RefColumns: []*schema.Column{CountriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "accounts_currencies_accounts",
				Columns:    []*schema.Column{AccountsColumns[6]},
				RefColumns: []*schema.Column{CurrenciesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "accounts_users_accounts",
				Columns:    []*schema.Column{AccountsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// BudgetsColumns holds the columns for the "budgets" table.
	BudgetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "month", Type: field.TypeInt},
		{Name: "year", Type: field.TypeInt},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "category_id", Type: field.TypeInt},
		{Name: "country_id", Type: field.TypeInt},
		{Name: "currency_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// BudgetsTable holds the schema information for the "budgets" table.
	BudgetsTable = &schema.Table{
		Name:       "budgets",
		Columns:    BudgetsColumns,
		PrimaryKey: []*schema.Column{BudgetsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "budgets_categories_budgets",
				Columns:    []*schema.Column{BudgetsColumns[4]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "budgets_countries_budgets",
				Columns:    []*schema.Column{BudgetsColumns[5]},
				RefColumns: []*schema.Column{CountriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "budgets_currencies_budgets",
				Columns:    []*schema.Column{BudgetsColumns[6]},
				RefColumns: []*schema.Column{CurrenciesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "budgets_users_budgets",
				Columns:    []*schema.Column{BudgetsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"income", "expense", "transfer"}},
		{Name: "color", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeInt},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "categories_users_categories",
				Columns:    []*schema.Column{CategoriesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// CountriesColumns holds the columns for the "countries" table.
	CountriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// CountriesTable holds the schema information for the "countries" table.
	CountriesTable = &schema.Table{
		Name:       "countries",
		Columns:    CountriesColumns,
		PrimaryKey: []*schema.Column{CountriesColumns[0]},
	}
	// CurrenciesColumns holds the columns for the "currencies" table.
	CurrenciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "symbol", Type: field.TypeString, Nullable: true},
		{Name: "decimal_places", Type: field.TypeInt, Default: 2},
	}
	// CurrenciesTable holds the schema information for the "currencies" table.
	CurrenciesTable = &schema.Table{
		Name:       "currencies",
		Columns:    CurrenciesColumns,
		PrimaryKey: []*schema.Column{CurrenciesColumns[0]},
	}
	// LoginAttemptsColumns holds the columns for the "login_attempts" table.
	LoginAttemptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Nullable: true},
		{Name: "ip_address", Type: field.TypeString},
		{Name: "success", Type: field.TypeBool},
		{Name: "attempted_at", Type: field.TypeTime},
	}
	// LoginAttemptsTable holds the schema information for the "login_attempts" table.
	LoginAttemptsTable = &schema.Table{
		Name:       "login_attempts",
		Columns:    LoginAttemptsColumns,
		PrimaryKey: []*schema.Column{LoginAttemptsColumns[0]},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "last_seen", Type: field.TypeTime},
		{Name: "ip_address", Type: field.TypeString},
		{Name: "user_agent_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "transaction_type", Type: field.TypeEnum, Enums: []string{"income", "expense", "transfer"}},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "transaction_date", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "account_id", Type: field.TypeInt},
		{Name: "category_id", Type: field.TypeInt},
		{Name: "transaction_linked_transaction", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transactions_accounts_transactions",
				Columns:    []*schema.Column{TransactionsColumns[6]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "transactions_categories_transactions",
				Columns:    []*schema.Column{TransactionsColumns[7]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "transactions_transactions_linked_transaction",
				Columns:    []*schema.Column{TransactionsColumns[8]},
				RefColumns: []*schema.Column{TransactionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		BudgetsTable,
		CategoriesTable,
		CountriesTable,
		CurrenciesTable,
		LoginAttemptsTable,
		SessionsTable,
		TransactionsTable,
		UsersTable,
	}
)

func init() {
	AccountsTable.ForeignKeys[0].RefTable = CountriesTable
	AccountsTable.ForeignKeys[1].RefTable = CurrenciesTable
	AccountsTable.ForeignKeys[2].RefTable = UsersTable
	BudgetsTable.ForeignKeys[0].RefTable = CategoriesTable
	BudgetsTable.ForeignKeys[1].RefTable = CountriesTable
	BudgetsTable.ForeignKeys[2].RefTable = CurrenciesTable
	BudgetsTable.ForeignKeys[3].RefTable = UsersTable
	CategoriesTable.ForeignKeys[0].RefTable = UsersTable
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
	TransactionsTable.ForeignKeys[0].RefTable = AccountsTable
	TransactionsTable.ForeignKeys[1].RefTable = CategoriesTable
	TransactionsTable.ForeignKeys[2].RefTable = TransactionsTable
}
