// Code generated by ent, DO NOT EDIT.

package ent

import (
	"budgot/internal/ent/budget"
	"budgot/internal/ent/category"
	"budgot/internal/ent/country"
	"budgot/internal/ent/currency"
	"budgot/internal/ent/predicate"
	"budgot/internal/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BudgetUpdate is the builder for updating Budget entities.
type BudgetUpdate struct {
	config
	hooks    []Hook
	mutation *BudgetMutation
}

// Where appends a list predicates to the BudgetUpdate builder.
func (_u *BudgetUpdate) Where(ps ...predicate.Budget) *BudgetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMonth sets the "month" field.
func (_u *BudgetUpdate) SetMonth(v int) *BudgetUpdate {
	_u.mutation.ResetMonth()
	_u.mutation.SetMonth(v)
	return _u
}

// SetNillableMonth sets the "month" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableMonth(v *int) *BudgetUpdate {
	if v != nil {
		_u.SetMonth(*v)
	}
	return _u
}

// AddMonth adds value to the "month" field.
func (_u *BudgetUpdate) AddMonth(v int) *BudgetUpdate {
	_u.mutation.AddMonth(v)
	return _u
}

// SetYear sets the "year" field.
func (_u *BudgetUpdate) SetYear(v int) *BudgetUpdate {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableYear(v *int) *BudgetUpdate {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *BudgetUpdate) AddYear(v int) *BudgetUpdate {
	_u.mutation.AddYear(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BudgetUpdate) SetAmount(v int64) *BudgetUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableAmount(v *int64) *BudgetUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BudgetUpdate) AddAmount(v int64) *BudgetUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *BudgetUpdate) SetIsActive(v bool) *BudgetUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableIsActive(v *bool) *BudgetUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BudgetUpdate) SetUpdatedAt(v time.Time) *BudgetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *BudgetUpdate) SetOwnerID(id int) *BudgetUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *BudgetUpdate) SetOwner(v *User) *BudgetUpdate {
	return _u.SetOwnerID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *BudgetUpdate) SetCategoryID(id int) *BudgetUpdate {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *BudgetUpdate) SetCategory(v *Category) *BudgetUpdate {
	return _u.SetCategoryID(v.ID)
}

// SetCountryID sets the "country" edge to the Country entity by ID.
func (_u *BudgetUpdate) SetCountryID(id int) *BudgetUpdate {
	_u.mutation.SetCountryID(id)
	return _u
}

// SetCountry sets the "country" edge to the Country entity.
func (_u *BudgetUpdate) SetCountry(v *Country) *BudgetUpdate {
	return _u.SetCountryID(v.ID)
}

// SetCurrencyID sets the "currency" edge to the Currency entity by ID.
func (_u *BudgetUpdate) SetCurrencyID(id int) *BudgetUpdate {
	_u.mutation.SetCurrencyID(id)
	return _u
}

// SetCurrency sets the "currency" edge to the Currency entity.
func (_u *BudgetUpdate) SetCurrency(v *Currency) *BudgetUpdate {
	return _u.SetCurrencyID(v.ID)
}

// Mutation returns the BudgetMutation object of the builder.
func (_u *BudgetUpdate) Mutation() *BudgetMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *BudgetUpdate) ClearOwner() *BudgetUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *BudgetUpdate) ClearCategory() *BudgetUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// ClearCountry clears the "country" edge to the Country entity.
func (_u *BudgetUpdate) ClearCountry() *BudgetUpdate {
	_u.mutation.ClearCountry()
	return _u
}

// ClearCurrency clears the "currency" edge to the Currency entity.
func (_u *BudgetUpdate) ClearCurrency() *BudgetUpdate {
	_u.mutation.ClearCurrency()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BudgetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BudgetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BudgetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BudgetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BudgetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := budget.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BudgetUpdate) check() error {
	if v, ok := _u.mutation.Month(); ok {
		if err := budget.MonthValidator(v); err != nil {
			return &ValidationError{Name: "month", err: fmt.Errorf(`ent: validator failed for field "Budget.month": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := budget.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Budget.amount": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Budget.owner"`)
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Budget.category"`)
	}
	if _u.mutation.CountryCleared() && len(_u.mutation.CountryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Budget.country"`)
	}
	if _u.mutation.CurrencyCleared() && len(_u.mutation.CurrencyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Budget.currency"`)
	}
	return nil
}

func (_u *BudgetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(budget.Table, budget.Columns, sqlgraph.NewFieldSpec(budget.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Month(); ok {
		_spec.SetField(budget.FieldMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonth(); ok {
		_spec.AddField(budget.FieldMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(budget.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(budget.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(budget.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(budget.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(budget.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(budget.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.OwnerTable,
			Columns: []string{budget.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.OwnerTable,
			Columns: []string{budget.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CategoryTable,
			Columns: []string{budget.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CategoryTable,
			Columns: []string{budget.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CountryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CountryTable,
			Columns: []string{budget.CountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(country.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CountryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CountryTable,
			Columns: []string{budget.CountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(country.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrencyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CurrencyTable,
			Columns: []string{budget.CurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(currency.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrencyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CurrencyTable,
			Columns: []string{budget.CurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(currency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BudgetUpdateOne is the builder for updating a single Budget entity.
type BudgetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BudgetMutation
}

// SetMonth sets the "month" field.
func (_u *BudgetUpdateOne) SetMonth(v int) *BudgetUpdateOne {
	_u.mutation.ResetMonth()
	_u.mutation.SetMonth(v)
	return _u
}

// SetNillableMonth sets the "month" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableMonth(v *int) *BudgetUpdateOne {
	if v != nil {
		_u.SetMonth(*v)
	}
	return _u
}

// AddMonth adds value to the "month" field.
func (_u *BudgetUpdateOne) AddMonth(v int) *BudgetUpdateOne {
	_u.mutation.AddMonth(v)
	return _u
}

// SetYear sets the "year" field.
func (_u *BudgetUpdateOne) SetYear(v int) *BudgetUpdateOne {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableYear(v *int) *BudgetUpdateOne {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *BudgetUpdateOne) AddYear(v int) *BudgetUpdateOne {
	_u.mutation.AddYear(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BudgetUpdateOne) SetAmount(v int64) *BudgetUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableAmount(v *int64) *BudgetUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BudgetUpdateOne) AddAmount(v int64) *BudgetUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *BudgetUpdateOne) SetIsActive(v bool) *BudgetUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableIsActive(v *bool) *BudgetUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BudgetUpdateOne) SetUpdatedAt(v time.Time) *BudgetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *BudgetUpdateOne) SetOwnerID(id int) *BudgetUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *BudgetUpdateOne) SetOwner(v *User) *BudgetUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *BudgetUpdateOne) SetCategoryID(id int) *BudgetUpdateOne {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *BudgetUpdateOne) SetCategory(v *Category) *BudgetUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// SetCountryID sets the "country" edge to the Country entity by ID.
func (_u *BudgetUpdateOne) SetCountryID(id int) *BudgetUpdateOne {
	_u.mutation.SetCountryID(id)
	return _u
}

// SetCountry sets the "country" edge to the Country entity.
func (_u *BudgetUpdateOne) SetCountry(v *Country) *BudgetUpdateOne {
	return _u.SetCountryID(v.ID)
}

// SetCurrencyID sets the "currency" edge to the Currency entity by ID.
func (_u *BudgetUpdateOne) SetCurrencyID(id int) *BudgetUpdateOne {
	_u.mutation.SetCurrencyID(id)
	return _u
}

// SetCurrency sets the "currency" edge to the Currency entity.
func (_u *BudgetUpdateOne) SetCurrency(v *Currency) *BudgetUpdateOne {
	return _u.SetCurrencyID(v.ID)
}

// Mutation returns the BudgetMutation object of the builder.
func (_u *BudgetUpdateOne) Mutation() *BudgetMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *BudgetUpdateOne) ClearOwner() *BudgetUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *BudgetUpdateOne) ClearCategory() *BudgetUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// ClearCountry clears the "country" edge to the Country entity.
func (_u *BudgetUpdateOne) ClearCountry() *BudgetUpdateOne {
	_u.mutation.ClearCountry()
	return _u
}

// ClearCurrency clears the "currency" edge to the Currency entity.
func (_u *BudgetUpdateOne) ClearCurrency() *BudgetUpdateOne {
	_u.mutation.ClearCurrency()
	return _u
}

// Where appends a list predicates to the BudgetUpdate builder.
func (_u *BudgetUpdateOne) Where(ps ...predicate.Budget) *BudgetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BudgetUpdateOne) Select(field string, fields ...string) *BudgetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Budget entity.
func (_u *BudgetUpdateOne) Save(ctx context.Context) (*Budget, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BudgetUpdateOne) SaveX(ctx context.Context) *Budget {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BudgetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BudgetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BudgetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := budget.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BudgetUpdateOne) check() error {
	if v, ok := _u.mutation.Month(); ok {
		if err := budget.MonthValidator(v); err != nil {
			return &ValidationError{Name: "month", err: fmt.Errorf(`ent: validator failed for field "Budget.month": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := budget.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Budget.amount": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Budget.owner"`)
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Budget.category"`)
	}
	if _u.mutation.CountryCleared() && len(_u.mutation.CountryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Budget.country"`)
	}
	if _u.mutation.CurrencyCleared() && len(_u.mutation.CurrencyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Budget.currency"`)
	}
	return nil
}

func (_u *BudgetUpdateOne) sqlSave(ctx context.Context) (_node *Budget, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(budget.Table, budget.Columns, sqlgraph.NewFieldSpec(budget.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Budget.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, budget.FieldID)
		for _, f := range fields {
			if !budget.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != budget.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Month(); ok {
		_spec.SetField(budget.FieldMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMonth(); ok {
		_spec.AddField(budget.FieldMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(budget.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(budget.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(budget.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(budget.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(budget.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(budget.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.OwnerTable,
			Columns: []string{budget.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.OwnerTable,
			Columns: []string{budget.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CategoryTable,
			Columns: []string{budget.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CategoryTable,
			Columns: []string{budget.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CountryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CountryTable,
			Columns: []string{budget.CountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(country.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CountryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CountryTable,
			Columns: []string{budget.CountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(country.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrencyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CurrencyTable,
			Columns: []string{budget.CurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(currency.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrencyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CurrencyTable,
			Columns: []string{budget.CurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(currency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Budget{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
