// Code generated by ent, DO NOT EDIT.

package ent

import (
	"budgot/internal/ent/currency"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Currency is the model entity for the Currency schema.
type Currency struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Symbol holds the value of the "symbol" field.
	Symbol string `json:"symbol,omitempty"`
	// DecimalPlaces holds the value of the "decimal_places" field.
	DecimalPlaces int `json:"decimal_places,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CurrencyQuery when eager-loading is set.
	Edges        CurrencyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CurrencyEdges holds the relations/edges for other nodes in the graph.
type CurrencyEdges struct {
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// Budgets holds the value of the budgets edge.
	Budgets []*Budget `json:"budgets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e CurrencyEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[0] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// BudgetsOrErr returns the Budgets value or an error if the edge
// was not loaded in eager-loading.
func (e CurrencyEdges) BudgetsOrErr() ([]*Budget, error) {
	if e.loadedTypes[1] {
		return e.Budgets, nil
	}
	return nil, &NotLoadedError{edge: "budgets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Currency) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case currency.FieldID, currency.FieldDecimalPlaces:
			values[i] = new(sql.NullInt64)
		case currency.FieldCode, currency.FieldName, currency.FieldSymbol:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Currency fields.
func (_m *Currency) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case currency.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case currency.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case currency.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case currency.FieldSymbol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field symbol", values[i])
			} else if value.Valid {
				_m.Symbol = value.String
			}
		case currency.FieldDecimalPlaces:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field decimal_places", values[i])
			} else if value.Valid {
				_m.DecimalPlaces = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Currency.
// This includes values selected through modifiers, order, etc.
func (_m *Currency) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccounts queries the "accounts" edge of the Currency entity.
func (_m *Currency) QueryAccounts() *AccountQuery {
	return NewCurrencyClient(_m.config).QueryAccounts(_m)
}

// QueryBudgets queries the "budgets" edge of the Currency entity.
func (_m *Currency) QueryBudgets() *BudgetQuery {
	return NewCurrencyClient(_m.config).QueryBudgets(_m)
}

// Update returns a builder for updating this Currency.
// Note that you need to call Currency.Unwrap() before calling this method if this Currency
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Currency) Update() *CurrencyUpdateOne {
	return NewCurrencyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Currency entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Currency) Unwrap() *Currency {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Currency is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Currency) String() string {
	var builder strings.Builder
	builder.WriteString("Currency(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("symbol=")
	builder.WriteString(_m.Symbol)
	builder.WriteString(", ")
	builder.WriteString("decimal_places=")
	builder.WriteString(fmt.Sprintf("%v", _m.DecimalPlaces))
	builder.WriteByte(')')
	return builder.String()
}

// Currencies is a parsable slice of Currency.
type Currencies []*Currency
