// Code generated by ent, DO NOT EDIT.

package ent

import (
	"budgot/internal/ent/loginattempt"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LoginAttempt is the model entity for the LoginAttempt schema.
type LoginAttempt struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// IPAddress holds the value of the "ip_address" field.
	IPAddress string `json:"ip_address,omitempty"`
	// Success holds the value of the "success" field.
	Success bool `json:"success,omitempty"`
	// AttemptedAt holds the value of the "attempted_at" field.
	AttemptedAt  time.Time `json:"attempted_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LoginAttempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case loginattempt.FieldSuccess:
			values[i] = new(sql.NullBool)
		case loginattempt.FieldID:
			values[i] = new(sql.NullInt64)
		case loginattempt.FieldUsername, loginattempt.FieldIPAddress:
			values[i] = new(sql.NullString)
		case loginattempt.FieldAttemptedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LoginAttempt fields.
func (_m *LoginAttempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case loginattempt.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case loginattempt.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case loginattempt.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				_m.IPAddress = value.String
			}
		case loginattempt.FieldSuccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field success", values[i])
			} else if value.Valid {
				_m.Success = value.Bool
			}
		case loginattempt.FieldAttemptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field attempted_at", values[i])
			} else if value.Valid {
				_m.AttemptedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LoginAttempt.
// This includes values selected through modifiers, order, etc.
func (_m *LoginAttempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LoginAttempt.
// Note that you need to call LoginAttempt.Unwrap() before calling this method if this LoginAttempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LoginAttempt) Update() *LoginAttemptUpdateOne {
	return NewLoginAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LoginAttempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LoginAttempt) Unwrap() *LoginAttempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LoginAttempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LoginAttempt) String() string {
	var builder strings.Builder
	builder.WriteString("LoginAttempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("ip_address=")
	builder.WriteString(_m.IPAddress)
	builder.WriteString(", ")
	builder.WriteString("success=")
	builder.WriteString(fmt.Sprintf("%v", _m.Success))
	builder.WriteString(", ")
	builder.WriteString("attempted_at=")
	builder.WriteString(_m.AttemptedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LoginAttempts is a parsable slice of LoginAttempt.
type LoginAttempts []*LoginAttempt
