// Code generated by ent, DO NOT EDIT.

package ent

import (
	"budgot/internal/ent/loginattempt"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoginAttemptCreate is the builder for creating a LoginAttempt entity.
type LoginAttemptCreate struct {
	config
	mutation *LoginAttemptMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (_c *LoginAttemptCreate) SetUsername(v string) *LoginAttemptCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *LoginAttemptCreate) SetNillableUsername(v *string) *LoginAttemptCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *LoginAttemptCreate) SetIPAddress(v string) *LoginAttemptCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetSuccess sets the "success" field.
func (_c *LoginAttemptCreate) SetSuccess(v bool) *LoginAttemptCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetAttemptedAt sets the "attempted_at" field.
func (_c *LoginAttemptCreate) SetAttemptedAt(v time.Time) *LoginAttemptCreate {
	_c.mutation.SetAttemptedAt(v)
	return _c
}

// SetNillableAttemptedAt sets the "attempted_at" field if the given value is not nil.
func (_c *LoginAttemptCreate) SetNillableAttemptedAt(v *time.Time) *LoginAttemptCreate {
	if v != nil {
		_c.SetAttemptedAt(*v)
	}
	return _c
}

// Mutation returns the LoginAttemptMutation object of the builder.
func (_c *LoginAttemptCreate) Mutation() *LoginAttemptMutation {
	return _c.mutation
}

// Save creates the LoginAttempt in the database.
func (_c *LoginAttemptCreate) Save(ctx context.Context) (*LoginAttempt, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LoginAttemptCreate) SaveX(ctx context.Context) *LoginAttempt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoginAttemptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoginAttemptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LoginAttemptCreate) defaults() {
	if _, ok := _c.mutation.AttemptedAt(); !ok {
		v := loginattempt.DefaultAttemptedAt()
		_c.mutation.SetAttemptedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LoginAttemptCreate) check() error {
	if _, ok := _c.mutation.IPAddress(); !ok {
		return &ValidationError{Name: "ip_address", err: errors.New(`ent: missing required field "LoginAttempt.ip_address"`)}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := loginattempt.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "LoginAttempt.ip_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "LoginAttempt.success"`)}
	}
	if _, ok := _c.mutation.AttemptedAt(); !ok {
		return &ValidationError{Name: "attempted_at", err: errors.New(`ent: missing required field "LoginAttempt.attempted_at"`)}
	}
	return nil
}

func (_c *LoginAttemptCreate) sqlSave(ctx context.Context) (*LoginAttempt, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LoginAttemptCreate) createSpec() (*LoginAttempt, *sqlgraph.CreateSpec) {
	var (
		_node = &LoginAttempt{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(loginattempt.Table, sqlgraph.NewFieldSpec(loginattempt.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(loginattempt.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(loginattempt.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(loginattempt.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.AttemptedAt(); ok {
		_spec.SetField(loginattempt.FieldAttemptedAt, field.TypeTime, value)
		_node.AttemptedAt = value
	}
	return _node, _spec
}

// LoginAttemptCreateBulk is the builder for creating many LoginAttempt entities in bulk.
type LoginAttemptCreateBulk struct {
	config
	err      error
	builders []*LoginAttemptCreate
}

// Save creates the LoginAttempt entities in the database.
func (_c *LoginAttemptCreateBulk) Save(ctx context.Context) ([]*LoginAttempt, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LoginAttempt, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoginAttemptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LoginAttemptCreateBulk) SaveX(ctx context.Context) []*LoginAttempt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoginAttemptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoginAttemptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
