// Code generated by ent, DO NOT EDIT.

package ent

import (
	"budgot/internal/ent/account"
	"budgot/internal/ent/budget"
	"budgot/internal/ent/category"
	"budgot/internal/ent/country"
	"budgot/internal/ent/currency"
	"budgot/internal/ent/loginattempt"
	"budgot/internal/ent/schema"
	"budgot/internal/ent/session"
	"budgot/internal/ent/transaction"
	"budgot/internal/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[0].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = accountDescName.Validators[0].(func(string) error)
	// accountDescIsActive is the schema descriptor for is_active field.
	accountDescIsActive := accountFields[2].Descriptor()
	// account.DefaultIsActive holds the default value on creation for the is_active field.
	account.DefaultIsActive = accountDescIsActive.Default.(bool)
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[3].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountFields[4].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	budgetFields := schema.Budget{}.Fields()
	_ = budgetFields
	// budgetDescMonth is the schema descriptor for month field.
	budgetDescMonth := budgetFields[0].Descriptor()
	// budget.MonthValidator is a validator for the "month" field. It is called by the builders before save.
	budget.MonthValidator = func() func(int) error {
		validators := budgetDescMonth.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(month int) error {
			for _, fn := range fns {
				if err := fn(month); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// budgetDescAmount is the schema descriptor for amount field.
	budgetDescAmount := budgetFields[2].Descriptor()
	// budget.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	budget.AmountValidator = budgetDescAmount.Validators[0].(func(int64) error)
	// budgetDescIsActive is the schema descriptor for is_active field.
	budgetDescIsActive := budgetFields[3].Descriptor()
	// budget.DefaultIsActive holds the default value on creation for the is_active field.
	budget.DefaultIsActive = budgetDescIsActive.Default.(bool)
	// budgetDescCreatedAt is the schema descriptor for created_at field.
	budgetDescCreatedAt := budgetFields[4].Descriptor()
	// budget.DefaultCreatedAt holds the default value on creation for the created_at field.
	budget.DefaultCreatedAt = budgetDescCreatedAt.Default.(func() time.Time)
	// budgetDescUpdatedAt is the schema descriptor for updated_at field.
	budgetDescUpdatedAt := budgetFields[5].Descriptor()
	// budget.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	budget.DefaultUpdatedAt = budgetDescUpdatedAt.Default.(func() time.Time)
	// budget.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	budget.UpdateDefaultUpdatedAt = budgetDescUpdatedAt.UpdateDefault.(func() time.Time)
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[0].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescColor is the schema descriptor for color field.
	categoryDescColor := categoryFields[2].Descriptor()
	// category.ColorValidator is a validator for the "color" field. It is called by the builders before save.
	category.ColorValidator = categoryDescColor.Validators[0].(func(string) error)
	// categoryDescIsActive is the schema descriptor for is_active field.
	categoryDescIsActive := categoryFields[3].Descriptor()
	// category.DefaultIsActive holds the default value on creation for the is_active field.
	category.DefaultIsActive = categoryDescIsActive.Default.(bool)
	countryFields := schema.Country{}.Fields()
	_ = countryFields
	// countryDescCode is the schema descriptor for code field.
	countryDescCode := countryFields[0].Descriptor()
	// country.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	country.CodeValidator = countryDescCode.Validators[0].(func(string) error)
	// countryDescName is the schema descriptor for name field.
	countryDescName := countryFields[1].Descriptor()
	// country.NameValidator is a validator for the "name" field. It is called by the builders before save.
	country.NameValidator = countryDescName.Validators[0].(func(string) error)
	currencyFields := schema.Currency{}.Fields()
	_ = currencyFields
	// currencyDescCode is the schema descriptor for code field.
	currencyDescCode := currencyFields[0].Descriptor()
	// currency.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	currency.CodeValidator = currencyDescCode.Validators[0].(func(string) error)
	// currencyDescName is the schema descriptor for name field.
	currencyDescName := currencyFields[1].Descriptor()
	// currency.NameValidator is a validator for the "name" field. It is called by the builders before save.
	currency.NameValidator = currencyDescName.Validators[0].(func(string) error)
	// currencyDescDecimalPlaces is the schema descriptor for decimal_places field.
	currencyDescDecimalPlaces := currencyFields[3].Descriptor()
	// currency.DefaultDecimalPlaces holds the default value on creation for the decimal_places field.
	currency.DefaultDecimalPlaces = currencyDescDecimalPlaces.Default.(int)
	loginattemptFields := schema.LoginAttempt{}.Fields()
	_ = loginattemptFields
	// loginattemptDescIPAddress is the schema descriptor for ip_address field.
	loginattemptDescIPAddress := loginattemptFields[1].Descriptor()
	// loginattempt.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	loginattempt.IPAddressValidator = loginattemptDescIPAddress.Validators[0].(func(string) error)
	// loginattemptDescAttemptedAt is the schema descriptor for attempted_at field.
	loginattemptDescAttemptedAt := loginattemptFields[3].Descriptor()
	// loginattempt.DefaultAttemptedAt holds the default value on creation for the attempted_at field.
	loginattempt.DefaultAttemptedAt = loginattemptDescAttemptedAt.Default.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescLastSeen is the schema descriptor for last_seen field.
	sessionDescLastSeen := sessionFields[2].Descriptor()
	// session.DefaultLastSeen holds the default value on creation for the last_seen field.
	session.DefaultLastSeen = sessionDescLastSeen.Default.(func() time.Time)
	// sessionDescIPAddress is the schema descriptor for ip_address field.
	sessionDescIPAddress := sessionFields[3].Descriptor()
	// session.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	session.IPAddressValidator = sessionDescIPAddress.Validators[0].(func(string) error)
	// sessionDescUserAgentHash is the schema descriptor for user_agent_hash field.
	sessionDescUserAgentHash := sessionFields[4].Descriptor()
	// session.UserAgentHashValidator is a validator for the "user_agent_hash" field. It is called by the builders before save.
	session.UserAgentHashValidator = sessionDescUserAgentHash.Validators[0].(func(string) error)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[5].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.IDValidator is a validator for the "id" field. It is called by the builders before save.
	session.IDValidator = sessionDescID.Validators[0].(func(string) error)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionFields[3].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[5].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
}
