// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Budget is the predicate function for budget builders.
type Budget func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Country is the predicate function for country builders.
type Country func(*sql.Selector)

// Currency is the predicate function for currency builders.
type Currency func(*sql.Selector)

// LoginAttempt is the predicate function for loginattempt builders.
type LoginAttempt func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
