// Code generated by ent, DO NOT EDIT.

package currency

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the currency type in the database.
	Label = "currency"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// FieldDecimalPlaces holds the string denoting the decimal_places field in the database.
	FieldDecimalPlaces = "decimal_places"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// EdgeBudgets holds the string denoting the budgets edge name in mutations.
	EdgeBudgets = "budgets"
	// Table holds the table name of the currency in the database.
	Table = "currencies"
	// AccountsTable is the table that holds the accounts relation/edge.
	AccountsTable = "accounts"
	// AccountsInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountsInverseTable = "accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "currency_id"
	// BudgetsTable is the table that holds the budgets relation/edge.
	BudgetsTable = "budgets"
	// BudgetsInverseTable is the table name for the Budget entity.
	// It exists in this package in order to avoid circular dependency with the "budget" package.
	BudgetsInverseTable = "budgets"
	// BudgetsColumn is the table column denoting the budgets relation/edge.
	BudgetsColumn = "currency_id"
)

// Columns holds all SQL columns for currency fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldName,
	FieldSymbol,
	FieldDecimalPlaces,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDecimalPlaces holds the default value on creation for the "decimal_places" field.
	DefaultDecimalPlaces int
)

// OrderOption defines the ordering options for the Currency queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySymbol orders the results by the symbol field.
func BySymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSymbol, opts...).ToFunc()
}

// ByDecimalPlaces orders the results by the decimal_places field.
func ByDecimalPlaces(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDecimalPlaces, opts...).ToFunc()
}

// ByAccountsCount orders the results by accounts count.
func ByAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountsStep(), opts...)
	}
}

// ByAccounts orders the results by accounts terms.
func ByAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBudgetsCount orders the results by budgets count.
func ByBudgetsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBudgetsStep(), opts...)
	}
}

// ByBudgets orders the results by budgets terms.
func ByBudgets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBudgetsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
	)
}
func newBudgetsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BudgetsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BudgetsTable, BudgetsColumn),
	)
}
