// Code generated by ent, DO NOT EDIT.

package currency

import (
	"budgot/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldName, v))
}

// Symbol applies equality check predicate on the "symbol" field. It's identical to SymbolEQ.
func Symbol(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldSymbol, v))
}

// DecimalPlaces applies equality check predicate on the "decimal_places" field. It's identical to DecimalPlacesEQ.
func DecimalPlaces(v int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldDecimalPlaces, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContainsFold(FieldName, v))
}

// SymbolEQ applies the EQ predicate on the "symbol" field.
func SymbolEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldSymbol, v))
}

// SymbolNEQ applies the NEQ predicate on the "symbol" field.
func SymbolNEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldSymbol, v))
}

// SymbolIn applies the In predicate on the "symbol" field.
func SymbolIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldSymbol, vs...))
}

// SymbolNotIn applies the NotIn predicate on the "symbol" field.
func SymbolNotIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldSymbol, vs...))
}

// SymbolGT applies the GT predicate on the "symbol" field.
func SymbolGT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldSymbol, v))
}

// SymbolGTE applies the GTE predicate on the "symbol" field.
func SymbolGTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldSymbol, v))
}

// SymbolLT applies the LT predicate on the "symbol" field.
func SymbolLT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldSymbol, v))
}

// SymbolLTE applies the LTE predicate on the "symbol" field.
func SymbolLTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldSymbol, v))
}

// SymbolContains applies the Contains predicate on the "symbol" field.
func SymbolContains(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContains(FieldSymbol, v))
}

// SymbolHasPrefix applies the HasPrefix predicate on the "symbol" field.
func SymbolHasPrefix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasPrefix(FieldSymbol, v))
}

// SymbolHasSuffix applies the HasSuffix predicate on the "symbol" field.
func SymbolHasSuffix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasSuffix(FieldSymbol, v))
}

// SymbolIsNil applies the IsNil predicate on the "symbol" field.
func SymbolIsNil() predicate.Currency {
	return predicate.Currency(sql.FieldIsNull(FieldSymbol))
}

// SymbolNotNil applies the NotNil predicate on the "symbol" field.
func SymbolNotNil() predicate.Currency {
	return predicate.Currency(sql.FieldNotNull(FieldSymbol))
}

// SymbolEqualFold applies the EqualFold predicate on the "symbol" field.
func SymbolEqualFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEqualFold(FieldSymbol, v))
}

// SymbolContainsFold applies the ContainsFold predicate on the "symbol" field.
func SymbolContainsFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContainsFold(FieldSymbol, v))
}

// DecimalPlacesEQ applies the EQ predicate on the "decimal_places" field.
func DecimalPlacesEQ(v int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldDecimalPlaces, v))
}

// DecimalPlacesNEQ applies the NEQ predicate on the "decimal_places" field.
func DecimalPlacesNEQ(v int) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldDecimalPlaces, v))
}

// DecimalPlacesIn applies the In predicate on the "decimal_places" field.
func DecimalPlacesIn(vs ...int) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldDecimalPlaces, vs...))
}

// DecimalPlacesNotIn applies the NotIn predicate on the "decimal_places" field.
func DecimalPlacesNotIn(vs ...int) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldDecimalPlaces, vs...))
}

// DecimalPlacesGT applies the GT predicate on the "decimal_places" field.
func DecimalPlacesGT(v int) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldDecimalPlaces, v))
}

// DecimalPlacesGTE applies the GTE predicate on the "decimal_places" field.
func DecimalPlacesGTE(v int) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldDecimalPlaces, v))
}

// DecimalPlacesLT applies the LT predicate on the "decimal_places" field.
func DecimalPlacesLT(v int) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldDecimalPlaces, v))
}

// DecimalPlacesLTE applies the LTE predicate on the "decimal_places" field.
func DecimalPlacesLTE(v int) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldDecimalPlaces, v))
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.Currency {
	return predicate.Currency(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.Currency {
	return predicate.Currency(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Currency) predicate.Currency {
	return predicate.Currency(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Currency) predicate.Currency {
	return predicate.Currency(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Currency) predicate.Currency {
	return predicate.Currency(sql.NotPredicates(p))
}
