// Code generated by ent, DO NOT EDIT.

package country

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the country type in the database.
	Label = "country"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// EdgeBudgets holds the string denoting the budgets edge name in mutations.
	EdgeBudgets = "budgets"
	// EdgeDefaultCurrency holds the string denoting the default_currency edge name in mutations.
	EdgeDefaultCurrency = "default_currency"
	// Table holds the table name of the country in the database.
	Table = "countries"
	// AccountsTable is the table that holds the accounts relation/edge.
	AccountsTable = "accounts"
	// AccountsInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountsInverseTable = "accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "country_id"
	// BudgetsTable is the table that holds the budgets relation/edge.
	BudgetsTable = "budgets"
	// BudgetsInverseTable is the table name for the Budget entity.
	// It exists in this package in order to avoid circular dependency with the "budget" package.
	BudgetsInverseTable = "budgets"
	// BudgetsColumn is the table column denoting the budgets relation/edge.
	BudgetsColumn = "country_id"
	// DefaultCurrencyTable is the table that holds the default_currency relation/edge.
	DefaultCurrencyTable = "countries"
	// DefaultCurrencyInverseTable is the table name for the Currency entity.
	// It exists in this package in order to avoid circular dependency with the "currency" package.
	DefaultCurrencyInverseTable = "currencies"
	// DefaultCurrencyColumn is the table column denoting the default_currency relation/edge.
	DefaultCurrencyColumn = "default_currency_id"
)

// Columns holds all SQL columns for country fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "countries"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"default_currency_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the Country queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAccountsCount orders the results by accounts count.
func ByAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountsStep(), opts...)
	}
}

// ByAccounts orders the results by accounts terms.
func ByAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBudgetsCount orders the results by budgets count.
func ByBudgetsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBudgetsStep(), opts...)
	}
}

// ByBudgets orders the results by budgets terms.
func ByBudgets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBudgetsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDefaultCurrencyField orders the results by default_currency field.
func ByDefaultCurrencyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDefaultCurrencyStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
	)
}
func newBudgetsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BudgetsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BudgetsTable, BudgetsColumn),
	)
}
func newDefaultCurrencyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DefaultCurrencyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, DefaultCurrencyTable, DefaultCurrencyColumn),
	)
}
