// Code generated by ent, DO NOT EDIT.

package loginattempt

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the loginattempt type in the database.
	Label = "login_attempt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldIPAddress holds the string denoting the ip_address field in the database.
	FieldIPAddress = "ip_address"
	// FieldSuccess holds the string denoting the success field in the database.
	FieldSuccess = "success"
	// FieldAttemptedAt holds the string denoting the attempted_at field in the database.
	FieldAttemptedAt = "attempted_at"
	// Table holds the table name of the loginattempt in the database.
	Table = "login_attempts"
)

// Columns holds all SQL columns for loginattempt fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldIPAddress,
	FieldSuccess,
	FieldAttemptedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	IPAddressValidator func(string) error
	// DefaultAttemptedAt holds the default value on creation for the "attempted_at" field.
	DefaultAttemptedAt func() time.Time
)

// OrderOption defines the ordering options for the LoginAttempt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByIPAddress orders the results by the ip_address field.
func ByIPAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPAddress, opts...).ToFunc()
}

// BySuccess orders the results by the success field.
func BySuccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccess, opts...).ToFunc()
}

// ByAttemptedAt orders the results by the attempted_at field.
func ByAttemptedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptedAt, opts...).ToFunc()
}
