// Code generated by ent, DO NOT EDIT.

package loginattempt

import (
	"budgot/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLTE(FieldID, id))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldUsername, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldIPAddress, v))
}

// Success applies equality check predicate on the "success" field. It's identical to SuccessEQ.
func Success(v bool) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldSuccess, v))
}

// AttemptedAt applies equality check predicate on the "attempted_at" field. It's identical to AttemptedAtEQ.
func AttemptedAt(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldAttemptedAt, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameIsNil applies the IsNil predicate on the "username" field.
func UsernameIsNil() predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldIsNull(FieldUsername))
}

// UsernameNotNil applies the NotNil predicate on the "username" field.
func UsernameNotNil() predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNotNull(FieldUsername))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldContainsFold(FieldUsername, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldContainsFold(FieldIPAddress, v))
}

// SuccessEQ applies the EQ predicate on the "success" field.
func SuccessEQ(v bool) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldSuccess, v))
}

// SuccessNEQ applies the NEQ predicate on the "success" field.
func SuccessNEQ(v bool) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNEQ(FieldSuccess, v))
}

// AttemptedAtEQ applies the EQ predicate on the "attempted_at" field.
func AttemptedAtEQ(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldAttemptedAt, v))
}

// AttemptedAtNEQ applies the NEQ predicate on the "attempted_at" field.
func AttemptedAtNEQ(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNEQ(FieldAttemptedAt, v))
}

// AttemptedAtIn applies the In predicate on the "attempted_at" field.
func AttemptedAtIn(vs ...time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldIn(FieldAttemptedAt, vs...))
}

// AttemptedAtNotIn applies the NotIn predicate on the "attempted_at" field.
func AttemptedAtNotIn(vs ...time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNotIn(FieldAttemptedAt, vs...))
}

// AttemptedAtGT applies the GT predicate on the "attempted_at" field.
func AttemptedAtGT(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGT(FieldAttemptedAt, v))
}

// AttemptedAtGTE applies the GTE predicate on the "attempted_at" field.
func AttemptedAtGTE(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGTE(FieldAttemptedAt, v))
}

// AttemptedAtLT applies the LT predicate on the "attempted_at" field.
func AttemptedAtLT(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLT(FieldAttemptedAt, v))
}

// AttemptedAtLTE applies the LTE predicate on the "attempted_at" field.
func AttemptedAtLTE(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLTE(FieldAttemptedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LoginAttempt) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LoginAttempt) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LoginAttempt) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.NotPredicates(p))
}
